![ATARRI logos](img/logos.png)

# 3.2 MPLNET lidar vs MONARCH dust forecast comparison: Processing forecasts

#### Objective

The objective of this notebook is to process MONARCH dust model data over the Barcelona station corresponding to the dates of the previously analysed dust event, so that it may be compared with MPLNET data.

## MONARCH extinction

Now, we will obtain the same dust extinction profile for our MONARCH datasets at the Barcelona station. Note that, in the [dust.aemet](https://dust.aemet.es/) products, we already have dust extinction. However, this product corresponds only to the surface level, and since we are interested in the entire vertical column, we will apply the following workflow:

- Extract species values from `od550_dust`, `dust_load` and `concdu`.
- Read the intermediate csv files and filter data.
- Calculate the dust extinction at each vertical level.
- Save the final output to a csv file.

## Importing libraries

In [10]:
import xarray as xr
import numpy as np
from pathlib import Path
import netCDF4 as nc
from netCDF4 import num2date
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

In [11]:
from IPython.utils.io import capture_output
with capture_output():
    %run ../functions/VT3-functions.ipynb

For this subsection, we will only need to call the `VT3-functions.ipynb` notebook. We will also need to reset our site coordinates, our data subdirectories and our output directory.

In [12]:
#%% SITE COORDINATES 
sites = {
    "Barcelona": {"latitude": 41.3860, "longitude": 2.1170}
    # you can add as many site coordinates as you wish in this list
}

In [13]:
directory_path_loaddu = Path("/shared/data/exp_to_interp/monarch/regional/3hourly/dust_load")
directory_path_od550du = Path("/shared/data/exp_to_interp/monarch/regional/3hourly/od550_dust")
directory_path_concdu = Path("/shared/data/exp_to_interp/monarch/regional/3hourly/sconc_dust")

In [14]:
output_base_path = Path("../csv")

In [15]:
start_date = datetime(2025, 3, 3)
end_date = datetime(2025, 3, 8)

## Pre-processing

To facilitate our MONARCH analysis, we will make use of the `process_monarch_variable()` function. This function will process each of the MONARCH datasets and save numerical data to csv files. In the case of `sconc_dust`, the output csv will include values at each altitude level. Each .csv is saved directly to our `/csv` folder.

In [16]:
# For dust concentration:
process_monarch_variable("sconc_dust", sites, directory_path_concdu, start_date, end_date, output_base_path)

# For dust load:
process_monarch_variable("dust_load", sites, directory_path_loaddu, start_date, end_date, output_base_path)

# For dust optical depth:
process_monarch_variable("od550_dust", sites, directory_path_od550du, start_date, end_date, output_base_path)

Processing site: Barcelona
Processing file: sconc_dust_2025030312.nc
Processing file: sconc_dust_2025030412.nc
Processing file: sconc_dust_2025030512.nc
Processing file: sconc_dust_2025030612.nc
CSV file saved to ../csv/sconc_dust_Barcelona.csv

Processing site: Barcelona
Processing file: dust_load_2025030312.nc
Processing file: dust_load_2025030412.nc
Processing file: dust_load_2025030512.nc
Processing file: dust_load_2025030612.nc
CSV file saved to ../csv/dust_load_Barcelona.csv

Processing site: Barcelona
Processing file: od550_dust_2025030312.nc
Processing file: od550_dust_2025030412.nc
Processing file: od550_dust_2025030512.nc
Processing file: od550_dust_2025030612.nc
CSV file saved to ../csv/od550_dust_Barcelona.csv

## Reading .csv files

Once the preprocessing is done, we will re-read the output csv files as data frames.

In [17]:
concdu_path = '../csv/sconc_dust_Barcelona.csv'
loaddu_path = '../csv/dust_load_Barcelona.csv'
od550du_path = '../csv/od550_dust_Barcelona.csv'

dust_conc_data = pd.read_csv(concdu_path)
loaddu_data = pd.read_csv(loaddu_path)
od550du_data = pd.read_csv(od550du_path)

If you look closely, you will notice that we again have two sets of data points at midnight.

In [18]:
dust_conc_data

,time,0.00,250.00,500.00,750.00,1000.00,1500.00,2000.00,3000.00,4000.00,5000.00,6000.00,8000.00,10000.00,12000.00
0,2025-03-04 00:00:00,2.387649e-09,3.095478e-09,1.452630e-08,3.144622e-08,3.078621e-08,4.555418e-08,4.318344e-08,6.400119e-08,3.312116e-09,1.410673e-09,1.430221e-09,6.434805e-11,1.241225e-13,1.009119e-19
1,2025-03-04 03:00:00,2.685390e-09,3.792238e-09,1.497859e-08,2.248090e-08,2.538781e-08,7.688739e-08,1.532948e-07,4.407160e-08,2.579770e-09,1.978591e-09,1.368650e-09,5.639573e-11,5.747515e-15,1.682543e-20
2,2025-03-04 06:00:00,4.173618e-09,5.473769e-09,1.482429e-08,3.493940e-08,5.151354e-08,8.736882e-08,9.273366e-08,1.988867e-08,4.662231e-09,1.845425e-09,9.794094e-10,4.411150e-11,1.481190e-13,4.326643e-20
3,2025-03-04 09:00:00,5.575906e-09,6.261387e-09,1.741249e-08,2.331086e-08,3.423384e-08,1.150821e-07,1.120279e-07,2.031249e-08,4.054840e-09,1.987563e-09,1.045998e-09,2.972990e-10,2.684365e-15,9.641685e-20
4,2025-03-04 12:00:00,4.298911e-09,4.780516e-09,1.695290e-08,3.162640e-08,3.322675e-08,7.609557e-08,7.620392e-08,6.337730e-08,3.950463e-08,1.923695e-09,9.403035e-10,2.730575e-10,1.664026e-15,6.627699e-19
5,2025-03-04 15:00:00,5.418448e-09,5.824409e-09,1.085326e-08,4.015672e-08,8.601853e-08,1.029196e-07,6.345603e-08,6.247596e-08,2.824519e-08,2.648393e-09,1.409497e-09,5.640848e-11,3.502266e-16,1.436675e-20
6,2025-03-04 18:00:00,8.676950e-10,7.058441e-10,4.627609e-09,7.054384e-08,1.366671e-07,3.032974e-08,3.988706e-09,2.041166e-09,6.310498e-09,6.006987e-09,4.982395e-09,4.703752e-11,1.167028e-17,3.144440e-21
7,2025-03-04 21:00:00,4.736556e-10,1.669133e-10,4.378369e-08,1.964156e-08,7.985785e-09,9.621727e-08,1.876273e-10,1.504522e-09,3.114932e-09,4.424830e-09,5.846431e-09,7.478172e-12,9.446154e-17,2.415674e-18
8,2025-03-05 00:00:00,8.814809e-09,1.166479e-08,4.088628e-08,1.050794e-07,1.283638e-07,1.347055e-07,9.043258e-08,2.042491e-08,4.464122e-09,1.125495e-09,1.545538e-09,3.578114e-12,3.833440e-15,7.470083e-18
9,2025-03-05 03:00:00,8.879549e-09,9.239462e-09,1.909430e-08,6.672966e-08,1.057941e-07,1.140676e-07,8.072585e-08,2.266081e-08,6.124726e-09,1.322842e-09,2.554032e-09,8.631143e-13,3.410306e-16,3.809472e-18
10,2025-03-05 06:00:00,7.184759e-09,7.060393e-09,7.678047e-09,3.158555e-08,6.643136e-08,9.940374e-08,7.010151e-08,2.797769e-08,6.319286e-09,2.073005e-09,1.376084e-09,2.421530e-12,3.651437e-15,3.284451e-18
11,2025-03-05 09:00:00,5.126514e-09,5.140699e-09,6.071089e-09,1.335168e-08,2.223094e-08,7.319916e-08,1.065527e-07,2.326757e-08,1.023855e-08,2.450440e-09,5.149796e-10,6.733226e-14,7.302622e-15,6.024692e-18
12,2025-03-05 12:00:00,6.287715e-09,6.529026e-09,8.013374e-09,1.464166e-08,2.635585e-08,4.045352e-08,8.036087e-08,3.089126e-08,1.747960e-08,3.880745e-09,1.579865e-10,1.429825e-13,3.872231e-16,6.929482e-18
13,2025-03-05 15:00:00,5.868567e-09,6.623370e-09,3.186005e-08,5.418154e-08,4.404819e-08,5.043974e-08,8.109733e-08,2.723324e-08,2.231932e-08,2.613303e-09,2.594733e-09,2.824021e-14,4.680151e-17,1.355979e-18
14,2025-03-05 18:00:00,4.024248e-09,4.325918e-09,1.887534e-08,3.838815e-08,4.182817e-08,6.753449e-08,7.261431e-08,2.530498e-08,2.377896e-08,3.623218e-09,2.831368e-09,1.881546e-12,2.083363e-13,1.655058e-18
15,2025-03-05 21:00:00,2.427959e-09,2.217260e-09,4.351064e-09,2.781091e-08,8.055212e-08,7.267901e-08,3.267523e-08,2.805786e-08,2.568420e-08,1.613015e-08,1.027672e-08,7.055663e-10,6.871558e-13,1.237661e-18
16,2025-03-06 00:00:00,5.268575e-09,6.421997e-09,1.408981e-08,2.054224e-08,2.545457e-08,7.657174e-08,5.133965e-08,2.849652e-08,1.391107e-08,1.311987e-08,1.185165e-08,5.299858e-10,9.824130e-13,7.452684e-18
17,2025-03-06 03:00:00,4.836498e-09,5.237823e-09,6.820064e-09,1.267798e-08,3.967683e-08,6.894768e-08,4.768610e-08,2.692511e-08,2.091904e-08,1.077897e-08,1.200070e-08,8.868588e-10,8.013947e-13,2.063018e-17
18,2025-03-06 06:00:00,2.377336e-09,2.800514e-09,5.578174e-09,1.490578e-08,2.457244e-08,4.726365e-08,4.545942e-08,4.623063e-08,1.901728e-08,8.809456e-09,9.962584e-09,1.648564e-09,4.586079e-13,1.551261e-18
19,2025-03-06 09:00:00,1.558190e-09,6.821884e-09,2.502768e-08,6.069718e-08,6.277276e-08,4.477392e-08,4.844079e-08,3.868093e-08,1.748278e-08,8.401021e-09,6.150241e-09,2.838114e-09,1.124881e-13,3.599339e-19
20,2025-03-06 12:00:00,3.899043e-09,9.400833e-09,3.073412e-08,3.636757e-08,3.618522e-08,3.982660e-08,4.969569e-08,4.535807e-08,2.227823e-08,8.947458e-09,5.736097e-09,3.399269e-09,6.863560e-14,3.325025e-19
21,2025-03-06 15:00:00,1.558691e-08,1.774352e-08,2.739081e-08,3.340051e-08,3.885151e-08,4.066684e-08,4.623845e-08,5.214457e-08,1.976052e-08,7.214073e-09,6.162166e-09,3.329630e-09,1.407785e-15,8.016336e-19
22,2025-03-06 18:00:00,7.605705e-09,7.466239e-09,5.527004e-09,2.769328e-09,5.936726e-09,7.831658e-09,1.536505e-08,4.141547e-08,1.806976e-08,1.180814e-08,6.205518e-09,2.429248e-09,7.571585e-14,5.802906e-19
23,2025-03-06 21:00:00,8.453240e-11,7.142411e-11,5.115037e-11,5.054578e-10,1.032887e-09,1.808222e-09,1.102577e-08,2.997472e-08,2.952018e-08,1.661369e-08,7.157069e-09,3.866774e-09,4.552910e-13,4.300143e-19
24,2025-03-07 00:00:00,1.045654e-09,1.056302e-09,1.079166e-09,1.898663e-09,2.715340e-09,6.316320e-09,8.141489e-09,1.013220e-08,1.515099e-08,8.353799e-09,5.324674e-09,4.884392e-09,7.905872e-14,3.299323e-17
25,2025-03-07 03:00:00,9.966935e-11,8.530342e-11,6.694956e-11,3.973078e-11,1.347587e-10,9.003777e-11,2.547821e-09,1.482636e-08,1.762185e-08,8.051081e-09,6.457968e-09,3.189433e-09,3.814441e-16,1.300374e-16
26,2025-03-07 06:00:00,5.488368e-10,4.056652e-10,1.537581e-10,6.905796e-11,4.655998e-11,1.170776e-09,5.509586e-09,1.215238e-08,1.675233e-08,8.122548e-09,8.373822e-09,6.175056e-10,8.626415e-15,2.082562e-16
27,2025-03-07 09:00:00,2.057822e-10,1.382418e-10,1.160753e-10,3.579137e-10,8.015383e-10,2.421712e-09,2.882118e-09,2.004561e-08,1.602483e-08,8.202418e-09,6.334563e-09,7.218238e-10,1.177018e-14,1.975744e-18
28,2025-03-07 12:00:00,1.761338e-10,2.731555e-10,7.471918e-10,8.878710e-10,8.054204e-10,4.593099e-09,6.432641e-09,3.156409e-08,1.682396e-08,8.590343e-09,5.591020e-09,1.871805e-10,3.822914e-14,4.622560e-21
29,2025-03-07 15:00:00,6.073613e-09,9.581773e-09,1.195859e-08,1.452667e-08,1.973662e-08,2.634725e-08,2.342256e-08,2.316425e-08,1.536193e-08,5.870536e-09,5.689328e-10,8.524923e-13,2.295879e-17,6.828086e-22
30,2025-03-07 18:00:00,5.285337e-10,1.529297e-09,6.148475e-09,7.997054e-09,1.348295e-08,4.161515e-08,3.721940e-08,2.289663e-08,1.292996e-08,3.479862e-09,4.198510e-10,7.634932e-14,5.689833e-19,3.020504e-22
31,2025-03-07 21:00:00,2.489635e-09,1.495735e-08,2.059907e-08,2.114046e-08,2.794613e-08,3.363584e-08,3.401479e-08,2.426409e-08,1.347894e-08,2.479902e-09,3.499725e-10,5.280259e-14,1.393446e-15,8.112801e-22

To get around this, we need to filter the data frames again, taking both values at `00:00:00` and averaging them to produce a unique value for midnight.

In [19]:
#%% REMOVE DUPLICATES 
dust_conc_cleaned = dust_conc_data.groupby('time', as_index=False).mean()
od550du_cleaned = od550du_data.groupby('time', as_index=False).mean()
loaddu_cleaned = loaddu_data.groupby('time', as_index=False).mean()
dust_conc_cleaned

,time,0.00,250.00,500.00,750.00,1000.00,1500.00,2000.00,3000.00,4000.00,5000.00,6000.00,8000.00,10000.00,12000.00
0,2025-03-04 00:00:00,2.387649e-09,3.095478e-09,1.452630e-08,3.144622e-08,3.078621e-08,4.555418e-08,4.318344e-08,6.400119e-08,3.312116e-09,1.410673e-09,1.430221e-09,6.434805e-11,1.241225e-13,1.009119e-19
1,2025-03-04 03:00:00,2.685390e-09,3.792238e-09,1.497859e-08,2.248090e-08,2.538781e-08,7.688739e-08,1.532948e-07,4.407160e-08,2.579770e-09,1.978591e-09,1.368650e-09,5.639573e-11,5.747515e-15,1.682543e-20
2,2025-03-04 06:00:00,4.173618e-09,5.473769e-09,1.482429e-08,3.493940e-08,5.151354e-08,8.736882e-08,9.273366e-08,1.988867e-08,4.662231e-09,1.845425e-09,9.794094e-10,4.411150e-11,1.481190e-13,4.326643e-20
3,2025-03-04 09:00:00,5.575906e-09,6.261387e-09,1.741249e-08,2.331086e-08,3.423384e-08,1.150821e-07,1.120279e-07,2.031249e-08,4.054840e-09,1.987563e-09,1.045998e-09,2.972990e-10,2.684365e-15,9.641685e-20
4,2025-03-04 12:00:00,4.298911e-09,4.780516e-09,1.695290e-08,3.162640e-08,3.322675e-08,7.609557e-08,7.620392e-08,6.337730e-08,3.950463e-08,1.923695e-09,9.403035e-10,2.730575e-10,1.664026e-15,6.627699e-19
5,2025-03-04 15:00:00,5.418448e-09,5.824409e-09,1.085326e-08,4.015672e-08,8.601853e-08,1.029196e-07,6.345603e-08,6.247596e-08,2.824519e-08,2.648393e-09,1.409497e-09,5.640848e-11,3.502266e-16,1.436675e-20
6,2025-03-04 18:00:00,8.676950e-10,7.058441e-10,4.627609e-09,7.054384e-08,1.366671e-07,3.032974e-08,3.988706e-09,2.041166e-09,6.310498e-09,6.006987e-09,4.982395e-09,4.703752e-11,1.167028e-17,3.144440e-21
7,2025-03-04 21:00:00,4.736556e-10,1.669133e-10,4.378369e-08,1.964156e-08,7.985785e-09,9.621727e-08,1.876273e-10,1.504522e-09,3.114932e-09,4.424830e-09,5.846431e-09,7.478172e-12,9.446154e-17,2.415674e-18
8,2025-03-05 00:00:00,8.814809e-09,1.166479e-08,4.088628e-08,1.050794e-07,1.283638e-07,1.347055e-07,9.043258e-08,2.042491e-08,4.464122e-09,1.125495e-09,1.545538e-09,3.578114e-12,3.833440e-15,7.470083e-18
9,2025-03-05 03:00:00,8.879549e-09,9.239462e-09,1.909430e-08,6.672966e-08,1.057941e-07,1.140676e-07,8.072585e-08,2.266081e-08,6.124726e-09,1.322842e-09,2.554032e-09,8.631143e-13,3.410306e-16,3.809472e-18
10,2025-03-05 06:00:00,7.184759e-09,7.060393e-09,7.678047e-09,3.158555e-08,6.643136e-08,9.940374e-08,7.010151e-08,2.797769e-08,6.319286e-09,2.073005e-09,1.376084e-09,2.421530e-12,3.651437e-15,3.284451e-18
11,2025-03-05 09:00:00,5.126514e-09,5.140699e-09,6.071089e-09,1.335168e-08,2.223094e-08,7.319916e-08,1.065527e-07,2.326757e-08,1.023855e-08,2.450440e-09,5.149796e-10,6.733226e-14,7.302622e-15,6.024692e-18
12,2025-03-05 12:00:00,6.287715e-09,6.529026e-09,8.013374e-09,1.464166e-08,2.635585e-08,4.045352e-08,8.036087e-08,3.089126e-08,1.747960e-08,3.880745e-09,1.579865e-10,1.429825e-13,3.872231e-16,6.929482e-18
13,2025-03-05 15:00:00,5.868567e-09,6.623370e-09,3.186005e-08,5.418154e-08,4.404819e-08,5.043974e-08,8.109733e-08,2.723324e-08,2.231932e-08,2.613303e-09,2.594733e-09,2.824021e-14,4.680151e-17,1.355979e-18
14,2025-03-05 18:00:00,4.024248e-09,4.325918e-09,1.887534e-08,3.838815e-08,4.182817e-08,6.753449e-08,7.261431e-08,2.530498e-08,2.377896e-08,3.623218e-09,2.831368e-09,1.881546e-12,2.083363e-13,1.655058e-18
15,2025-03-05 21:00:00,2.427959e-09,2.217260e-09,4.351064e-09,2.781091e-08,8.055212e-08,7.267901e-08,3.267523e-08,2.805786e-08,2.568420e-08,1.613015e-08,1.027672e-08,7.055663e-10,6.871558e-13,1.237661e-18
16,2025-03-06 00:00:00,5.268575e-09,6.421997e-09,1.408981e-08,2.054224e-08,2.545457e-08,7.657174e-08,5.133965e-08,2.849652e-08,1.391107e-08,1.311987e-08,1.185165e-08,5.299858e-10,9.824130e-13,7.452684e-18
17,2025-03-06 03:00:00,4.836498e-09,5.237823e-09,6.820064e-09,1.267798e-08,3.967683e-08,6.894768e-08,4.768610e-08,2.692511e-08,2.091904e-08,1.077897e-08,1.200070e-08,8.868588e-10,8.013947e-13,2.063018e-17
18,2025-03-06 06:00:00,2.377336e-09,2.800514e-09,5.578174e-09,1.490578e-08,2.457244e-08,4.726365e-08,4.545942e-08,4.623063e-08,1.901728e-08,8.809456e-09,9.962584e-09,1.648564e-09,4.586079e-13,1.551261e-18
19,2025-03-06 09:00:00,1.558190e-09,6.821884e-09,2.502768e-08,6.069718e-08,6.277276e-08,4.477392e-08,4.844079e-08,3.868093e-08,1.748278e-08,8.401021e-09,6.150241e-09,2.838114e-09,1.124881e-13,3.599339e-19
20,2025-03-06 12:00:00,3.899043e-09,9.400833e-09,3.073412e-08,3.636757e-08,3.618522e-08,3.982660e-08,4.969569e-08,4.535807e-08,2.227823e-08,8.947458e-09,5.736097e-09,3.399269e-09,6.863560e-14,3.325025e-19
21,2025-03-06 15:00:00,1.558691e-08,1.774352e-08,2.739081e-08,3.340051e-08,3.885151e-08,4.066684e-08,4.623845e-08,5.214457e-08,1.976052e-08,7.214073e-09,6.162166e-09,3.329630e-09,1.407785e-15,8.016336e-19
22,2025-03-06 18:00:00,7.605705e-09,7.466239e-09,5.527004e-09,2.769328e-09,5.936726e-09,7.831658e-09,1.536505e-08,4.141547e-08,1.806976e-08,1.180814e-08,6.205518e-09,2.429248e-09,7.571585e-14,5.802906e-19
23,2025-03-06 21:00:00,8.453240e-11,7.142411e-11,5.115037e-11,5.054578e-10,1.032887e-09,1.808222e-09,1.102577e-08,2.997472e-08,2.952018e-08,1.661369e-08,7.157069e-09,3.866774e-09,4.552910e-13,4.300143e-19
24,2025-03-07 00:00:00,1.045654e-09,1.056302e-09,1.079166e-09,1.898663e-09,2.715340e-09,6.316320e-09,8.141489e-09,1.013220e-08,1.515099e-08,8.353799e-09,5.324674e-09,4.884392e-09,7.905872e-14,3.299323e-17
25,2025-03-07 03:00:00,9.966935e-11,8.530342e-11,6.694956e-11,3.973078e-11,1.347587e-10,9.003777e-11,2.547821e-09,1.482636e-08,1.762185e-08,8.051081e-09,6.457968e-09,3.189433e-09,3.814441e-16,1.300374e-16
26,2025-03-07 06:00:00,5.488368e-10,4.056652e-10,1.537581e-10,6.905796e-11,4.655998e-11,1.170776e-09,5.509586e-09,1.215238e-08,1.675233e-08,8.122548e-09,8.373822e-09,6.175056e-10,8.626415e-15,2.082562e-16
27,2025-03-07 09:00:00,2.057822e-10,1.382418e-10,1.160753e-10,3.579137e-10,8.015383e-10,2.421712e-09,2.882118e-09,2.004561e-08,1.602483e-08,8.202418e-09,6.334563e-09,7.218238e-10,1.177018e-14,1.975744e-18
28,2025-03-07 12:00:00,1.761338e-10,2.731555e-10,7.471918e-10,8.878710e-10,8.054204e-10,4.593099e-09,6.432641e-09,3.156409e-08,1.682396e-08,8.590343e-09,5.591020e-09,1.871805e-10,3.822914e-14,4.622560e-21
29,2025-03-07 15:00:00,6.073613e-09,9.581773e-09,1.195859e-08,1.452667e-08,1.973662e-08,2.634725e-08,2.342256e-08,2.316425e-08,1.536193e-08,5.870536e-09,5.689328e-10,8.524923e-13,2.295879e-17,6.828086e-22
30,2025-03-07 18:00:00,5.285337e-10,1.529297e-09,6.148475e-09,7.997054e-09,1.348295e-08,4.161515e-08,3.721940e-08,2.289663e-08,1.292996e-08,3.479862e-09,4.198510e-10,7.634932e-14,5.689833e-19,3.020504e-22
31,2025-03-07 21:00:00,2.489635e-09,1.495735e-08,2.059907e-08,2.114046e-08,2.794613e-08,3.363584e-08,3.401479e-08,2.426409e-08,1.347894e-08,2.479902e-09,3.499725e-10,5.280259e-14,1.393446e-15,8.112801e-22

Next, we need to collect our time and altitude data in variables.

In [20]:
time_dust_conc = dust_conc_data['time']
time_loaddu = loaddu_data['time']
time_od550du = od550du_data['time']

In [21]:
altitudes = [float(col) for col in dust_conc_cleaned.columns[1:]]
altitudes

[0.0,
 250.0,
 500.0,
 750.0,
 1000.0,
 1500.0,
 2000.0,
 3000.0,
 4000.0,
 5000.0,
 6000.0,
 8000.0,
 10000.0,
 12000.0]

As we are going to calculate dust extinction, we need to ensure we match all variables to the same time step.

In [22]:
common_times = set(dust_conc_cleaned['time']).intersection(
    od550du_cleaned['time']
).intersection(
    loaddu_cleaned['time']
)

In [23]:
# Filter each dataset to include only rows with common times
dust_conc_aligned = dust_conc_cleaned[dust_conc_cleaned['time'].isin(common_times)]
od550du_aligned = od550du_cleaned[od550du_cleaned['time'].isin(common_times)]
loaddu_aligned = loaddu_cleaned[loaddu_cleaned['time'].isin(common_times)]

time_dust_conc_aligned = dust_conc_aligned['time']
time_dust_conc_aligned = pd.to_datetime(time_dust_conc_aligned)
dust_conc = dust_conc_aligned.drop(columns=['time'])

time_od550du_aligned = od550du_aligned['time']
time_od550du_aligned = pd.to_datetime(time_od550du_aligned)
od550du = od550du_aligned.drop(columns=['time'])

time_loaddu_aligned = loaddu_aligned['time']
time_loaddu_aligned = pd.to_datetime(time_loaddu_aligned)
loaddu = loaddu_aligned.drop(columns=['time'])

## Calculating dust extinction and saving output

Dust extinction can be calculated with the following formula:

$$
\text{dust extinction} = \left(\frac{\text{dust optical depth at 550nm}}{\text{dust load}}\right) \cdot \text{dust concentration}
$$

Since our `concdu` variable has different altitude levels, we will obtain an extinction result per each level. For the calculation to work, we need to transform `concdu` and the `od550_dust / dust_load` ratio to arrays.

In [24]:
ratio = (od550du / loaddu)
ratio = np.array(ratio)
concdu = np.array(dust_conc)
dust_ext_monarch = ratio * concdu
dust_ext_monarch

array([[1.22883886e-06, 1.59313352e-06, 7.47617505e-06, 1.61842620e-05,
        1.58445802e-05, 2.34451307e-05, 2.22249979e-05, 3.29391560e-05,
        1.70462952e-06, 7.26023818e-07, 7.36084279e-07, 3.31176778e-08,
        6.38814951e-11, 5.19358269e-17],
       [1.30416063e-06, 1.84170177e-06, 7.27435800e-06, 1.09178585e-05,
        1.23296005e-05, 3.73403930e-05, 7.44476641e-05, 2.14033900e-05,
        1.25286657e-06, 9.60903787e-07, 6.64685298e-07, 2.73886108e-08,
        2.79128325e-12, 8.17127807e-18],
       [2.20915767e-06, 2.89734681e-06, 7.84671463e-06, 1.84939414e-05,
        2.72668785e-05, 4.62456040e-05, 4.90852949e-05, 1.05273661e-05,
        2.46778736e-06, 9.76810383e-07, 5.18415829e-07, 2.33488649e-08,
        7.84015907e-11, 2.29015617e-17],
       [2.94736474e-06, 3.30970323e-06, 9.20405877e-06, 1.23218727e-05,
        1.80956472e-05, 6.08312060e-05, 5.92167485e-05, 1.07369665e-05,
        2.14334558e-06, 1.05060501e-06, 5.52903333e-07, 1.57149110e-07,
        1.41892703e-12, 5.09649282e-17],
       [2.14851197e-06, 2.38920829e-06, 8.47272985e-06, 1.58062551e-05,
        1.66060798e-05, 3.80310798e-05, 3.80852311e-05, 3.16747369e-05,
        1.97436411e-05, 9.61425194e-07, 4.69945327e-07, 1.36468831e-07,
        8.31647599e-13, 3.31239453e-16],
       [2.78921113e-06, 2.99818463e-06, 5.58684428e-06, 2.06711556e-05,
        4.42790705e-05, 5.29791063e-05, 3.26647529e-05, 3.21602475e-05,
        1.45395510e-05, 1.36329223e-06, 7.25555495e-07, 2.90369394e-08,
        1.80283335e-13, 7.39545593e-18],
       [5.78585267e-07, 4.70661939e-07, 3.08572274e-06, 4.70391415e-05,
        9.11306285e-05, 2.02240875e-05, 2.65969794e-06, 1.36106428e-06,
        4.20788580e-06, 4.00550194e-06, 3.32229660e-06, 3.13649578e-08,
        7.78182625e-15, 2.09673522e-18],
       [3.05816894e-07, 1.07767963e-07, 2.82690487e-05, 1.26816229e-05,
        5.15604168e-06, 6.21229204e-05, 1.21142028e-07, 9.71398511e-07,
        2.01116362e-06, 2.85690272e-06, 3.77476276e-06, 4.82830040e-09,
        6.09893315e-14, 1.55968614e-15],
       [4.57627179e-06, 6.05586235e-06, 2.12264077e-05, 5.45527376e-05,
        6.66409787e-05, 6.99333441e-05, 4.69487274e-05, 1.06037375e-05,
        2.31758119e-06, 5.84308706e-07, 8.02377065e-07, 1.85760374e-09,
        1.99015823e-12, 3.87814757e-15],
       [4.70074849e-06, 4.89128326e-06, 1.01083381e-05, 3.53260451e-05,
        5.60064080e-05, 6.03863199e-05, 4.27354966e-05, 1.19964165e-05,
        3.24237128e-06, 7.00300035e-07, 1.35208011e-06, 4.56924473e-10,
        1.80538334e-13, 2.01669812e-15],
       [3.99361640e-06, 3.92448784e-06, 4.26780805e-06, 1.75566849e-05,
        3.69255740e-05, 5.52531238e-05, 3.89656105e-05, 1.55512715e-05,
        3.51254655e-06, 1.15227038e-06, 7.64890242e-07, 1.34599661e-09,
        2.02963469e-12, 1.82564766e-15],
       [2.90135987e-06, 2.90938761e-06, 3.43594403e-06, 7.55640801e-06,
        1.25816390e-05, 4.14271970e-05, 6.03037216e-05, 1.31683239e-05,
        5.79452363e-06, 1.38683072e-06, 2.91453613e-07, 3.81068143e-11,
        4.13293213e-12, 3.40968545e-15],
       [3.57273447e-06, 3.70984949e-06, 4.55326896e-06, 8.31951714e-06,
        1.49756237e-05, 2.29860416e-05, 4.56617468e-05, 1.75526832e-05,
        9.93205882e-06, 2.20507314e-06, 8.97693235e-08, 8.12439029e-11,
        2.20023524e-13, 3.93739219e-15],
       [3.34152690e-06, 3.77130720e-06, 1.81409199e-05, 3.08506426e-05,
        2.50807755e-05, 2.87200858e-05, 4.61763316e-05, 1.55064443e-05,
        1.27084871e-05, 1.48799879e-06, 1.47742560e-06, 1.60798047e-11,
        2.66484994e-14, 7.72086263e-16],
       [2.48286314e-06, 2.66898646e-06, 1.16456250e-05, 2.36845603e-05,
        2.58069662e-05, 4.16671420e-05, 4.48012652e-05, 1.56125588e-05,
        1.46710445e-05, 2.23543773e-06, 1.74688568e-06, 1.16086824e-09,
        1.28538437e-10, 1.02113088e-15],
       [1.90444016e-06, 1.73917265e-06, 3.41288384e-06, 2.18142985e-05,
        6.31834027e-05, 5.70078994e-05, 2.56297727e-05, 2.20079985e-05,
        2.01461515e-05, 1.26521501e-05, 8.06084166e-06, 5.53431465e-07,
        5.38990707e-10, 9.70795158e-16],
       [4.19220114e-06, 5.10997776e-06, 1.12112543e-05, 1.63454436e-05,
        2.02541845e-05, 6.09280749e-05, 4.08509175e-05, 2.26746608e-05,
        1.10690302e-05, 1.04394698e-05, 9.43035060e-06, 4.21709267e-07,
        7.81705220e-10, 5.93009456e-15],
       [3.55790339e-06, 3.85313232e-06, 5.01708686e-06, 9.32638275e-06,
        2.91877155e-05, 5.07204183e-05, 3.50796229e-05, 1.98070884e-05,
        1.53888010e-05, 7.92939990e-06, 8.82814807e-06, 6.52405506e-07,
        5.89534977e-10, 1.51763088e-14],
       [1.67119932e-06, 1.96868183e-06, 3.92129753e-06, 1.04783362e-05,
        1.72737258e-05, 3.32250033e-05, 3.19566803e-05, 3.24988154e-05,
        1.33686065e-05, 6.19279679e-06, 7.00341330e-06, 1.15889384e-06,
        3.22388277e-10, 1.09049232e-15],
       [1.04649808e-06, 4.58165468e-06, 1.68088701e-05, 4.07649089e-05,
        4.21588952e-05, 3.00706728e-05, 3.25333795e-05, 2.59785498e-05,
        1.17416300e-05, 5.64222067e-06, 4.13057124e-06, 1.90610958e-06,
        7.55482459e-11, 2.41735703e-16],
       [2.55548012e-06, 6.16141962e-06, 2.01435119e-05, 2.38357431e-05,
        2.37162287e-05, 2.61028319e-05, 3.25711535e-05, 2.97282262e-05,
        1.46014193e-05, 5.86427216e-06, 3.75950759e-06, 2.22792194e-06,
        4.49846021e-11, 2.17926159e-16],
       [1.07434557e-05, 1.22299219e-05, 1.88794309e-05, 2.30216885e-05,
        2.67788482e-05, 2.80300901e-05, 3.18703836e-05, 3.59412448e-05,
        1.36201623e-05, 4.97238302e-06, 4.24734381e-06, 2.29498578e-06,
        9.70332077e-13, 5.52535182e-16],
       [6.30580270e-06, 6.19017304e-06, 4.58237557e-06, 2.29601805e-06,
        4.92207137e-06, 6.49313774e-06, 1.27389849e-05, 3.43370949e-05,
        1.49814264e-05, 9.78999249e-06, 5.14492398e-06, 2.01406171e-06,
        6.27751420e-11, 4.81112275e-16],
       [7.31388628e-08, 6.17973485e-08, 4.42561656e-08, 4.37330641e-07,
        8.93671050e-07, 1.56450392e-06, 9.53968104e-06, 2.59346349e-05,
        2.55413575e-05, 1.43744414e-05, 6.19241694e-06, 3.34559795e-06,
        3.93925477e-10, 3.72055648e-16],
       [1.22113692e-06, 1.23357247e-06, 1.26027307e-06, 2.21729867e-06,
        3.17103219e-06, 7.37633366e-06, 9.50780447e-06, 1.18326033e-05,
        1.76936469e-05, 9.75574404e-06, 6.21826738e-06, 5.70409667e-06,
        9.23264592e-11, 3.85301976e-14],
       [1.18928151e-07, 1.01786337e-07, 7.98860172e-08, 4.74078338e-08,
        1.60797697e-07, 1.07435491e-07, 3.04012896e-06, 1.76912095e-05,
        2.10268646e-05, 9.60676658e-06, 7.70582174e-06, 3.80571755e-06,
        4.55149416e-13, 1.55164078e-13],
       [6.42424692e-07, 4.74839451e-07, 1.79976992e-07, 8.08337610e-08,
        5.44994108e-08, 1.37041748e-06, 6.44908361e-06, 1.42246099e-05,
        1.96089500e-05, 9.50760931e-06, 9.80173069e-06, 7.22802992e-07,
        1.00973960e-11, 2.43768184e-13],
       [2.30742333e-07, 1.55009718e-07, 1.30154490e-07, 4.01326408e-07,
        8.98760035e-07, 2.71545085e-06, 3.23170184e-06, 2.24770209e-05,
        1.79685393e-05, 9.19732111e-06, 7.10290673e-06, 8.09376576e-07,
        1.31978286e-11, 2.21539022e-15],
       [1.77682011e-07, 2.75556544e-07, 7.53759585e-07, 8.95675460e-07,
        8.12500066e-07, 4.63347246e-06, 6.48918368e-06, 3.18415392e-05,
        1.69718430e-05, 8.66585234e-06, 5.64016521e-06, 1.88825842e-07,
        3.85651731e-11, 4.66319192e-18],
       [5.04627980e-06, 7.96104519e-06, 9.93583330e-06, 1.20695295e-05,
        1.63982290e-05, 2.18906927e-05, 1.94607051e-05, 1.92460841e-05,
        1.27635020e-05, 4.87755233e-06, 4.72699544e-07, 7.08295816e-10,
        1.90753804e-14, 5.67313574e-19],
       [4.29785005e-07, 1.24357066e-06, 4.99972349e-06, 6.50292288e-06,
        1.09638625e-05, 3.38399714e-05, 3.02655095e-05, 1.86187354e-05,
        1.05141868e-05, 2.82970132e-06, 3.41408058e-07, 6.20845802e-11,
        4.62677172e-16, 2.45616731e-19],
       [1.73157515e-06, 1.04030425e-05, 1.43269383e-05, 1.47034839e-05,
        1.94369175e-05, 2.33941889e-05, 2.36577560e-05, 1.68760115e-05,
        9.37479009e-06, 1.72480564e-06, 2.43410662e-07, 3.67249270e-11,
        9.69161120e-13, 5.64256423e-19]])

Finally, we can save our resulting extinction (in /m units), together with the MONARCH altitudes, in a csv file with the same `save_to_csv()` function we used previously. We will use this output in the following notebook.

In [25]:
csv_name = "MONARCH_Barcelona_20250304_20250308"

save_to_csv(time_dust_conc_aligned, dust_ext_monarch, csv_name, output_base_path, altitudes)

CSV file saved to ../csv/MONARCH_Barcelona_20250304_20250308.csv

## References and further reading

The analysis, main script and auxiliary functions of this notebook have been adapted from their original version, provided by Carlotta Gilè (BSC-CNS).

<table style="width:100%;">
    <tr>
        <td style="text-align: center;"><a href="VT3-1-MPLNET_extinction.ipynb" style="font-size: 18px;">⬅ Previous</a></td>
        <td style="text-align: center;"><a href="VT3-3-MPLNET_MONARCH_daily_avg.ipynb" style="font-size: 18px;">Next ➡</a></td>
    </tr
</table>